#!/usr/bin/python3
#+
# inotipy example: watch one or more specified paths, and report
# all events on them. Invoke this script as follows:
#
#     watch_path_multi «path» ...
#
# where the arguments are the paths to watch. This alternate
# version creates a separate task to watch each specified path.
#
# Copyright 2020 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>. This
# script is licensed CC0
# <https://creativecommons.org/publicdomain/zero/1.0/>; do with it
# what you will.
#-

import sys
import asyncio
import getopt
import inotify

loop = asyncio.get_event_loop()

timeout = None
opts, args = getopt.getopt \
  (
    sys.argv[1:],
    "",
    ["timeout="]
  )
for keyword, value in opts :
    if keyword == "--timeout" :
        timeout = float(value)
        assert timeout > 0
    #end if
#end for
if len(args) == 0 :
    raise getopt.GetoptError("nothing to watch")
#end if

async def watch(path) :
    watcher = inotify.Watcher.create()
    watcher.watch(path, inotify.IN.ALL_EVENTS)
    while True :
        event = await watcher.get(timeout)
        if event != None :
            sys.stdout.write("%s -- got event: %s\n" % (repr(path), repr(event)))
        else :
            sys.stdout.write("%s -- no event.\n" % repr(path))
        #end if
    #end while
#end watch

async def mainline() :
    await asyncio.wait(list(loop.create_task(watch(path)) for path in args))
#end mainline

loop.run_until_complete(mainline())
