#!/usr/bin/python3
#+
# inotipy example: watch one or more specified paths, and report
# all events on them. Invoke this script as follows:
#
#     watch_path «path» ...
#
# where the arguments are the paths to watch.
#
# Copyright 2018 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>. This
# script is licensed CC0
# <https://creativecommons.org/publicdomain/zero/1.0/>; do with it
# what you will.
#-

import sys
import asyncio
import getopt
import inotify

loop = asyncio.get_event_loop()

timeout = None
opts, args = getopt.getopt \
  (
    sys.argv[1:],
    "",
    ["timeout="]
  )
for keyword, value in opts :
    if keyword == "--timeout" :
        timeout = float(value)
        assert timeout > 0
    #end if
#end for
if len(args) == 0 :
    raise getopt.GetoptError("nothing to watch")
#end if

async def mainline() :
    watcher = inotify.Watcher.create()
    for path in args :
        watcher.watch(path, inotify.IN.ALL_EVENTS)
    #end for
    sys.stdout.write("watching: %s\n" % ", ".join("%s" % w.pathname for w in watcher.watches))
    while True :
        event = await watcher.get(timeout)
        if event != None :
            sys.stdout.write("Got event: %s\n" % repr(event))
        else :
            sys.stdout.write("No event.\n")
        #end if
    #end while
#end mainline

loop.run_until_complete(mainline())
