#!/usr/bin/python3
#+
# inotipy example: watch one or more specified paths, and report
# all events on them. Invoke this script as follows:
#
#     watch_path_alt «path» ...
#
# where the arguments are the paths to watch. This alternate version
# uses an async-for instead of a while-loop.
#
# Copyright 2019 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>. This
# script is licensed CC0
# <https://creativecommons.org/publicdomain/zero/1.0/>; do with it
# what you will.
#-

import sys
import asyncio
import getopt
import inotify

loop = asyncio.get_event_loop()

timeout = None
stop_on_timeout = False
stop_on = set()
opts, args = getopt.getopt \
  (
    sys.argv[1:],
    "",
    ["stop-on-timeout", "timeout="]
  )
for keyword, value in opts :
    if keyword == "--stop-on-timeout" :
        stop_on.add(inotify.STOP_ON.TIMEOUT)
    elif keyword == "--timeout" :
        timeout = float(value)
        assert timeout > 0
    #end if
#end for
if len(args) == 0 :
    raise getopt.GetoptError("nothing to watch")
#end if

async def mainline() :
    watcher = inotify.Watcher.create()
    for path in args :
        watcher.watch(path, inotify.IN.ALL_EVENTS)
    #end for
    sys.stdout.write("watching: %s\n" % ", ".join("%s" % w.pathname for w in watcher.watches))
    async for event in watcher.iter_async(stop_on = stop_on, timeout = timeout) :
        if event != None :
            sys.stdout.write("Got event: %s\n" % repr(event))
        else :
            sys.stdout.write("No event.\n")
        #end if
    #end for
#end mainline

loop.run_until_complete(mainline())
